name: ZAP-TEST

on: 
  push:
    branches: [ NBA-2 ]

jobs:
  test-frontend:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Build UI
        run: docker build -t datatrain-ui -f react/nba-analyzer/Dockerfile .
      - name: Run UI
        run: docker run -d -p 3000:3000 datatrain-ui
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://localhost:3000'
          cmd_options: '-a'
  test-backend:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Build
        run: docker build -t datatrain-nba -f nba_graphql/Dockerfile .
      - name: Run
        run: docker run -d -p 8080:8080 datatrain-nba
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://localhost:8080'
          cmd_options: '-a'